<?php
/**
 * @file
 * Adds a node slug /url class to the <body> tag.
 */

/**
 * Implements hook_preprocess_html().
 */
function body_node_url_class_preprocess_html(&$variables) {
  // Add node url to the body class.
    $current_url = \Drupal::service('path.current')->getPath();
    if ( ! $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage()) {
      $url_alias = \Drupal::service('path.alias_manager')->getAliasByPath($current_url);
      $url_alias = ltrim($url_alias, '/');
      $variables['attributes']['class'][] = 'path-' . \Drupal\Component\Utility\Html::cleanCssIdentifier($url_alias);
    }
    else {
      $variables['attributes']['class'][] = 'path-home';
    }
    
}

